apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-python
  labels:
    app: k8s-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-python
  template:
    metadata:
      labels:
        app: k8s-python
    spec:
      containers:
      - name: k8s-python
        image: tim5672s/k82-python-fastapi:0.0.1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            memory: 400Mi